version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - pitch

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    network_mode: "host"
    restart: always
    volumes:
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      /bin/sh -c "
      certbot certonly --standalone --non-interactive --agree-tos --keep-until-expiring --email admin@targetly.ru -d pitch.targetly.ru &&
      trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;
      "

  pitch:
    image: ghcr.io/trgtly/pitch:latest
    container_name: pitch
    restart: unless-stopped
    # Exposing internally, no need for ports mapped to host
    # because nginx will route to it.
